-- Source: chapters/ch31_adjunction.tex:112

/-
Chapter 31: Adjunctions, free constructions, and forgetful views.
This file mirrors the Lean snippets used in chapters/ch31_adjunction.tex.
The code intentionally avoids Mathlib's CategoryTheory API.
-/

namespace Ch31Adjunction

/-- A deliberately tiny monoid structure for teaching. -/
structure TinyMonoid (M : Type) where
  unit : M
  op : M -> M -> M
  unit_left : forall x : M, op unit x = x
  unit_right : forall x : M, op x unit = x
  assoc : forall x y z : M,
    op (op x y) z = op x (op y z)

/-- Lists form the free monoid on a type. -/
def listMonoid (A : Type) : TinyMonoid (List A) where
  unit := []
  op := List.append
  unit_left := by
    intro xs
    rfl
  unit_right := by
    intro xs
    induction xs with
    | nil => rfl
    | cons x xs ih =>
        simp [List.append, ih]
  assoc := by
    intro xs ys zs
    induction xs with
    | nil => rfl
    | cons x xs ih =>
        simp [List.append, ih]

/-- The underlying type of a monoid object: a forgetful view. -/
structure MonoidObject where
  Carrier : Type
  monoid : TinyMonoid Carrier

/-- Forget the monoid structure and keep only the carrier type. -/
def forget (X : MonoidObject) : Type := X.Carrier

/-- The free list monoid generated by a type. -/
def freeList (A : Type) : MonoidObject where
  Carrier := List A
  monoid := listMonoid A

/-- Extend an element-level interpretation to a list-level interpretation. -/
def foldMap {A M : Type} (mon : TinyMonoid M)
    (f : A -> M) : List A -> M
  | [] => mon.unit
  | x :: xs => mon.op (f x) (foldMap mon f xs)

theorem foldMap_nil {A M : Type}
    (mon : TinyMonoid M) (f : A -> M) :
    foldMap mon f [] = mon.unit := by
  rfl

theorem foldMap_singleton {A M : Type}
    (mon : TinyMonoid M) (f : A -> M) (a : A) :
    foldMap mon f [a] = f a := by
  simp [foldMap, mon.unit_right]
